### ISSUE TITLE
Open Questions

### ISSUE THREAD

**Issue by SeanROlszewski** [SwiftFest/ios-app#12]
* Does the list of speakers need to be dynamic? It's very likely we know this before the app gets deployed. I could see this being important, but maybe lower priority?
* Does the list of volunteers need to be dynamic? Same idea as above - maybe this is important, but not as important as having a list altogether?
* How passionate are we about having push notifications for the application?
* Do we care about localizing time so the agenda respects the user's time preferences?

**Comment by mdiasdev** [comment]
my 0.02$

The only reason I can see to have the speakers and/or volunteers be dynamic is in case some gets sick or otherwise needs to cancel last minute.

If we have time, I think doing a local push 5-10 minutes before a talk you marked as interesting is going to happen might be a good feature. But I think that could be one of the last things we try to implement.

Localizing is always good when you have a diverse audience. That said, it can be expensive and take a while to get back -- and I'm not totally sure we have the while. Maybe have all user facing strings be wrapped in `NSLocalizableString()` for just in case?

**Comment by BasThomas** [comment]
I think the localization part was only considering timezones, @mdiasdev. I don't think localizing the app should be necessary, although wrapping user-facing strings in an `NSLocalizedString` is never a bad idea. 😃

Re dynamic lists: we have never had this as a high enough priority for [try! Swift](https://github.com/tryswift/trySwiftAppFinal) and as far as I know it has not been too big of a deal.

**Comment by ZevEisenberg** [comment]
My preference for localization would be to use SwiftGen to set it up. Who knows - maybe some international attendees will volunteer to localize! I can set up SwiftGen if people like that approach. But I’m also fine just not localizing - it’s bound to cost dev time, and since the conference is in English, I think we have a reasonable expectation that people will be able to understand it in the app.

**Comment by ZevEisenberg** [comment]
Oh, and we should absolutely localize times and dates. That’s always the right answer IMHO, and using date for matters is way less error-prone than trying to do it yourself. We just need to make sure we use time zones appropriately, since people may be viewing the app in different time zones, but we want to format all dates in Eastern time.

**Comment by mdiasdev** [comment]
I've never used SwiftGen, but in the 2min read through the README it seems like it'd be good/easy to use to enforce consistency

**Comment by SeanROlszewski** [comment]
I’m cool using SwiftGen. I think it’s a good tool for the tedious work of
styles, etc. 👌

Going forward, all stories with user-facing date/times need to localize the
date/times otherwise they won’t be merged. We’ll need to get a README
together for this. I can throw one together.

**Comment by SeanROlszewski** [comment]
I just made a pull request that includes the new readme.

On an unrelated note, do we want to have a commit template for all issues that deliver a new feature to the app? Do we want to have standards around keeping WIP or intermediary commits out of master?

My answer to these 2 questions is yes, but I didn't want to be a dictator and impose my own opinions/standards on this. I fall on the side of wanting to have a rebase strategy that squashes out WIP/non-atomic commits.

**Comment by ZevEisenberg** [comment]
@SeanROlszewski I propose closing this issue

**Comment by SeanROlszewski** [comment]
@ZevEisenberg proposal approved. This is now closed.
