### ISSUE TITLE
Bug: Day 1 workshop/session swapped

### ISSUE THREAD

**Issue by mdiasdev** [SwiftFest/ios-app#45]
It looks like "Back to Front to Left Wrist" is listed as a talk instead of a workshop (perhaps mixed up with "Functional Magic in Swift")

**Comment by hisaac** [comment]
Hey @mdiasdev, thanks for reporting this. This is now fixed by PR #47.

**Comment by ZevEisenberg** [comment]
We plan to submit this change to the App Store tonight. If we want to also back-fix it for version 1.1 of the app, all we'd need to do is to rearrange the website's [_data/sessions.yml](https://github.com/SwiftFest/swiftfest-site/blob/gh-pages/_data/sessions.yml) file to have all the sessions listed in chronological order. No need to change the IDs - just the order of the items in the file. Probably not worth it, since everyone should just get the latest version of the app.
